apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-structured-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentic-structured-service
  template:
    metadata:
      labels:
        app: agentic-structured-service
    spec:
      imagePullSecrets:
      - name: acr-auth
      volumes:
      - name: health-proxy-volume
        configMap:
          name: health-proxy-configmap
      containers:
      - name: agentic-structured-service
        image: recfluxdemoacr.azurecr.io/agentic-structured-service:latest
        ports:
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: CORS_ORIGIN
          value: "*"
        - name: THUMBNAIL_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: THUMBNAIL_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENROUTER_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_SUPABASE_URL
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_WEBHOOK_SECRET
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: KAFKA_BROKERS
        - name: VERCEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: VERCEL_TOKEN
      - name: health-proxy
        image: node:18-slim
        command: ["node", "/health-proxy/health-proxy.js"]
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: "agentic-structured-service"
        volumeMounts:
        - name: health-proxy-volume
          mountPath: /health-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: agentic-structured-service
spec:
  selector:
    app: agentic-structured-service
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP 