apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-structured-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentic-structured-service
  template:
    metadata:
      labels:
        app: agentic-structured-service
    spec:
      containers:
      - name: agentic-structured-service
        image: ${CONTAINER_REGISTRY}/agentic-structured-service:${IMAGE_TAG}
        ports:
        - containerPort: 3001
        env:
        - name: CORS_ORIGIN
          value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: agentic-structured-service
spec:
  selector:
    app: agentic-structured-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP 