apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: api.4.156.13.98.nip.io
    http:
      paths:
      - path: /accessibility
        pathType: Prefix
        backend:
          service:
            name: recflux-tools-accessibility-service
            port:
              number: 3002
      - path: /kafka
        pathType: Prefix
        backend:
          service:
            name: kafka-producer-service
            port:
              number: 3004
      - path: /agentic
        pathType: Prefix
        backend:
          service:
            name: agentic-structured-service
            port:
              number: 3001
      - path: /deploy
        pathType: Prefix
        backend:
          service:
            name: code-deploy-service
            port:
              number: 3003 