apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-deploy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-deploy-service
  template:
    metadata:
      labels:
        app: code-deploy-service
    spec:
      imagePullSecrets:
      - name: acr-auth
      containers:
      - name: code-deploy-service
        image: recfluxdemoacr.azurecr.io/code-deploy-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: VERCEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: VERCEL_TOKEN
        - name: VERCEL_ORG_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: VERCEL_ORG_ID
        - name: VERCEL_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: VERCEL_PROJECT_ID
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: code-deploy-service
spec:
  selector:
    app: code-deploy-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP 