apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer-service
  template:
    metadata:
      labels:
        app: kafka-producer-service
    spec:
      containers:
      - name: kafka-producer-service
        image: ${CONTAINER_REGISTRY}/kafka-producer-service:${IMAGE_TAG}
        ports:
        - containerPort: 3004
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: CORS_ORIGIN
          value: "*"
        - name: THUMBNAIL_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: THUMBNAIL_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENROUTER_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_SUPABASE_URL
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_WEBHOOK_SECRET
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: VERCEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: VERCEL_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
spec:
  selector:
    app: kafka-producer-service
  ports:
  - port: 3004
    targetPort: 3004
  type: ClusterIP 