apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - zookeeper.yaml
  - kafka.yaml
  - recflux-tools-accessibility-service.yaml
  - kafka-producer-service.yaml
  - agentic-structured-service.yaml
  - code-deploy-service.yaml
  - nextjs-app.yaml
  - configmap.yaml
  - api-ingress.yaml
  - persistent-volume.yaml
  - app-secrets.yaml 