apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# Define the common tag for all images
images:
- name: recfluxdemoacr.azurecr.io/agentic-structured-service
  newTag: ${IMAGE_TAG}
- name: recfluxdemoacr.azurecr.io/kafka-producer-service
  newTag: ${IMAGE_TAG}
- name: recfluxdemoacr.azurecr.io/nextjs-app
  newTag: ${IMAGE_TAG}
- name: recfluxdemoacr.azurecr.io/recflux-tools-accessibility-service
  newTag: ${IMAGE_TAG}
- name: recfluxdemoacr.azurecr.io/code-deploy-service
  newTag: ${IMAGE_TAG}

resources:
  - zookeeper.yaml
  - kafka.yaml
  - recflux-tools-accessibility-service.yaml
  - kafka-producer-service.yaml
  - agentic-structured-service.yaml
  - code-deploy-service.yaml
  - nextjs-app.yaml
  - configmap.yaml
  - api-ingress.yaml
  - persistent-volume.yaml
  - unified-load-balancer.yaml 