apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      imagePullSecrets:
      - name: acr-auth
      containers:
      - name: nextjs-app
        image: recfluxdemoacr.azurecr.io/nextjs-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api_url
        - name: AGENTIC_STRUCTURED_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AGENTIC_STRUCTURED_URL
        - name: CODE_DEPLOY_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CODE_DEPLOY_URL
        - name: KAFKA_PRODUCER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_PRODUCER_URL
        - name: ACCESSIBILITY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ACCESSIBILITY_SERVICE_URL
        # Secret references for API keys
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_SUPABASE_URL
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_WEBHOOK_SECRET
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENROUTER_API_KEY
        - name: THUMBNAIL_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: THUMBNAIL_API_KEY
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
        - name: VERCEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: VERCEL_TOKEN
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  selector:
    app: nextjs-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-app-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: app.4.156.13.98.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-app-service
            port:
              number: 80 