apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      imagePullSecrets:
      - name: acr-auth
      containers:
      - name: nextjs-app
        image: recfluxdemoacr.azurecr.io/nextjs-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api_url
        - name: AGENTIC_STRUCTURED_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AGENTIC_STRUCTURED_URL
        - name: CODE_DEPLOY_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CODE_DEPLOY_URL
        - name: KAFKA_PRODUCER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_PRODUCER_URL
        - name: ACCESSIBILITY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ACCESSIBILITY_SERVICE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  selector:
    app: nextjs-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: app.4.156.13.98.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-app-service
            port:
              number: 80 