apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-app
        image: ${CONTAINER_REGISTRY}/nextjs-app:${IMAGE_TAG}
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api_url
        - name: THUMBNAIL_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: THUMBNAIL_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENROUTER_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_SUPABASE_URL
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_WEBHOOK_SECRET
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: KAFKA_BROKERS
        - name: VERCEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: VERCEL_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-app
spec:
  selector:
    app: nextjs-app
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-app-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: ${APP_HOSTNAME}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextjs-app
            port:
              number: 80 