apiVersion: apps/v1
kind: Deployment
metadata:
  name: recflux-tools-accessibility-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recflux-tools-accessibility-service
  template:
    metadata:
      labels:
        app: recflux-tools-accessibility-service
    spec:
      containers:
      - name: recflux-tools-accessibility-service
        image: ${CONTAINER_REGISTRY}/recflux-tools-accessibility-service:${IMAGE_TAG}
        ports:
        - containerPort: 3002
        env:
        - name: KAFKA_PRODUCER_URL
          value: "http://kafka-producer-service:3004"
        - name: THUMBNAIL_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: THUMBNAIL_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENROUTER_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OPENAI_API_KEY
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ANDROID
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_SUPABASE_URL
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_WEBHOOK_SECRET
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SUPABASE_SERVICE_ROLE_KEY
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: KAFKA_BROKERS
        - name: VERCEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: VERCEL_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: recflux-tools-accessibility-service
spec:
  selector:
    app: recflux-tools-accessibility-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP 