apiVersion: v1
kind: Service
metadata:
  name: unified-services-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
  - name: accessibility
    port: 3002
    targetPort: 3002
    protocol: TCP
  - name: agentic-structured
    port: 3001
    targetPort: 3001
    protocol: TCP
  - name: kafka-producer
    port: 3004
    targetPort: 3004
    protocol: TCP
  - name: code-deploy
    port: 3003
    targetPort: 3003
    protocol: TCP
  selector:
    app: lb-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lb-proxy
  template:
    metadata:
      labels:
        app: lb-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 3001
        - containerPort: 3002
        - containerPort: 3003
        - containerPort: 3004
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-lb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-lb-config
data:
  default.conf: |
    # Global settings
    client_max_body_size 50M;
    proxy_connect_timeout 180s;
    proxy_send_timeout 180s;
    proxy_read_timeout 180s;
    
    # WebSocket support
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    
    server {
      listen 80;
      server_name _;
      
      location /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'healthy';
      }
    }
    
    server {
      listen 3001;
      
      location / {
        proxy_pass http://agentic-structured-service:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        # AI service may need longer timeouts for processing
        proxy_read_timeout 300s;
        client_max_body_size 50M;
      }
    }
    
    server {
      listen 3002;
      
      location / {
        proxy_pass http://recflux-tools-accessibility-service:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        # Accessibility testing needs extended timeouts
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 600s; # 10 minutes for long-running tests
        client_max_body_size 50M;
      }
    }
    
    server {
      listen 3003;
      
      location / {
        proxy_pass http://code-deploy-service:3003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        # Code deployment may take time
        proxy_read_timeout 300s;
        client_max_body_size 50M;
      }
    }
    
    server {
      listen 3004;
      
      location / {
        proxy_pass http://kafka-producer-service:3004;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        # Kafka operations may involve larger payloads
        client_max_body_size 500M;
      }
    } 